version: "3"
services:
  web:
    container_name: webMYT
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/myportfolio
    depends_on:
      - db
    ports:
      - 80:80

  db:
    container_name: dbMYT
    image: postgres
    restart: always
    env_file:
      - .env
  #nginx:
  #  container_name: nginxMYT
  #  image: jonasal/nginx-certbot:latest
  #  restart: unless-stopped
  #  env_file:
  #    - ./nginx-certbot.env
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - nginx_secrets:/etc/letsencrypt
  #    - ./user_conf.d:/etc/nginx/user_conf.d
  #  depends_on:
  #    - web
  cadvisor:
    container_name: cadvisorMYT
    image: gcr.io/cadvisor/cadvisor:latest 
    restart: unless-stopped
    #volumes: 
    #  - /:/rootfs:ro 
    #  - /var/run:/var/run:rw 
    #  - /sys:/sys:ro 
    #  - /var/lib/docker/:/var/lib/docker:ro 

volumes:
  nginx_secrets:
  my_database: