version: "3"
services:
  web:
    container_name: webMYT
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/coolest_app
    depends_on:
      - db

  db:
    container_name: dbMYT
    image: postgres
    restart: always
    env_file:
      - .env
   
  cadvisor:
    container_name: cadvisorMYT
    image: gcr.io/cadvisor/cadvisor:latest 
    restart: unless-stopped
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
volumes:
  nginx_secrets:
  my_database:

