global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
      monitor: 'monitoring' 

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus
    static_configs: 
      - targets: ['192.168.xxx.xxx:9090']

  - job_name: node-exporter
    metrics_path: /node-exporter
    static_configs: 
      - targets: ['192.168.xxx.xxx:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    metrics_path: /cadvisor
    static_configs: 
      - targets: ['192.168.xxx.xxx:8080']