"""empty message

Revision ID: 4516845b5c05
Revises: 
Create Date: 2021-08-10 23:12:37.264249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4516845b5c05"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
