name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Set up Python failed
        if: ${{ failure() }}
        run:  curl -s -X POST "${{ secrets.DISCORD_WEBHOOKLINT }}" -d "content=  SET UP PYTHON ERROR"

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Install Python failed
        if: ${{ failure() }}
        run:  curl -s -X POST "${{ secrets.DISCORD_WEBHOOKLINT }}" -d "content=  INSTALL PYTHON ERROR "

      - name: Run linters
        uses: wearerequired/lint-action@v1.10.0
        with:
          black: true
          flake8: true
          flake8_args: "--exclude=python3-virtualenv/,migrations,env --max-line-length=200"

      - name: Format failed
        if: ${{ failure() }}
        run:  curl -s -X POST "${{ secrets.DISCORD_WEBHOOKLINT }}" -d "content=  FORMAT ERROR "

      - name: Test discord channel
        run:  curl -s -X POST "${{ secrets.DISCORD_WEBHOOKLINT }}" -d "content=  I can send messages :wink:"